"""
Devil ERP — PDF Report Generator
Generates: invoices, GST reports, balance sheets, P&L — all with Devil ERP branding.
"""

from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import mm
from pathlib import Path
from datetime import datetime
from core.config import BASE_DIR, APP_NAME, COMPANY, LEAD_DEV, SUPPORT_EMAIL, CURRENCY_SYMBOL

REPORTS_DIR = BASE_DIR / "reports" / "exports"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

LOGO_PATH = BASE_DIR / "assets" / "logo.png"

def generate_invoice_pdf(invoice: dict, items: list, party: dict, company: dict) -> str:
    """Generate a GST-compliant invoice PDF."""
    filename = f"Invoice_{invoice['invoice_number']}_{datetime.now().strftime('%Y%m%d')}.pdf"
    output_path = REPORTS_DIR / filename

    doc = SimpleDocTemplate(str(output_path), pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    # Header with logo
    if LOGO_PATH.exists():
        story.append(Image(str(LOGO_PATH), width=80, height=40))
    story.append(Spacer(1, 4*mm))

    title_style = ParagraphStyle('title', fontSize=16, fontName='Helvetica-Bold', textColor=colors.HexColor('#89b4fa'))
    story.append(Paragraph("TAX INVOICE", title_style))
    story.append(Spacer(1, 4*mm))

    # Company & party info
    info_data = [
        [Paragraph(f"<b>{company.get('name', APP_NAME)}</b>", styles['Normal']),
         Paragraph(f"<b>Bill To:</b> {party.get('name', '')}", styles['Normal'])],
        [company.get('address', ''), party.get('address', '')],
        [f"GSTIN: {company.get('gstin', 'N/A')}", f"GSTIN: {party.get('gstin', 'N/A')}"],
        [f"Invoice No: {invoice.get('invoice_number', '')}", f"Date: {invoice.get('invoice_date', '')}"],
    ]
    info_table = Table(info_data, colWidths=[90*mm, 90*mm])
    story.append(info_table)
    story.append(Spacer(1, 6*mm))

    # Items table
    table_data = [["#", "Product", "Qty", "Rate", "Disc%", "GST%", "Amount"]]
    for i, item in enumerate(items, 1):
        table_data.append([
            str(i), item.get('name', ''), str(item.get('qty', 0)),
            f"{CURRENCY_SYMBOL}{item.get('rate', 0):.2f}",
            f"{item.get('discount', 0)}%",
            f"{item.get('gst_rate', 0)}%",
            f"{CURRENCY_SYMBOL}{item.get('amount', 0):.2f}"
        ])

    items_table = Table(table_data, colWidths=[10*mm, 55*mm, 20*mm, 25*mm, 20*mm, 20*mm, 30*mm])
    items_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#313244')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#89b4fa')),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#45475a')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#1e1e2e'), colors.HexColor('#2a2a3e')]),
        ('TEXTCOLOR', (0, 1), (-1, -1), colors.HexColor('#cdd6f4')),
    ]))
    story.append(items_table)
    story.append(Spacer(1, 4*mm))

    # Totals
    totals_data = [
        ["Subtotal", f"{CURRENCY_SYMBOL}{invoice.get('subtotal', 0):.2f}"],
        ["CGST", f"{CURRENCY_SYMBOL}{invoice.get('cgst', 0):.2f}"],
        ["SGST", f"{CURRENCY_SYMBOL}{invoice.get('sgst', 0):.2f}"],
        ["IGST", f"{CURRENCY_SYMBOL}{invoice.get('igst', 0):.2f}"],
        ["TOTAL", f"{CURRENCY_SYMBOL}{invoice.get('total', 0):.2f}"],
    ]
    totals_table = Table(totals_data, colWidths=[140*mm, 40*mm])
    totals_table.setStyle(TableStyle([
        ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
        ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
        ('TEXTCOLOR', (0, -1), (-1, -1), colors.HexColor('#89b4fa')),
        ('LINEABOVE', (0, -1), (-1, -1), 1, colors.HexColor('#89b4fa')),
    ]))
    story.append(totals_table)
    story.append(Spacer(1, 8*mm))

    # Footer
    footer_style = ParagraphStyle('footer', fontSize=9, textColor=colors.HexColor('#6c7086'), alignment=1)
    story.append(Paragraph(f"Generated by {APP_NAME} | {COMPANY} | {SUPPORT_EMAIL} | Lead Dev: {LEAD_DEV}", footer_style))

    doc.build(story)
    return str(output_path)
